# Generated by Django 3.0.6 on 2020-05-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezenbucks_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product_temp', models.CharField(blank=True, choices=[('HOT', 'HOT'), ('ICE', 'ICE'), ('NONE', 'NONE')], max_length=10, null=True)),
                ('product_size', models.CharField(blank=True, choices=[('short', 'SHORT'), ('tall', 'TALL'), ('grande', 'GRANDE'), ('venti', 'VENTI')], max_length=10, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezenbucks_main.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezenbucks_main.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
